"""create initial tables

Revision ID: dafa3b84b108
Revises: 
Create Date: 2026-09-20 12:19:01.832810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dafa3b84b108'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('facility_type', sa.String(length=100), nullable=False),
    sa.Column('address_street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_iso', sa.String(length=3), nullable=False),
    sa.Column('phone_primary', sa.String(length=20), nullable=False),
    sa.Column('email_contact', sa.String(length=255), nullable=False),
    sa.Column('geo_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geo_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_index(op.f('ix_hospitals_code'), 'hospitals', ['code'], unique=True)
    op.create_index(op.f('ix_hospitals_state_province'), 'hospitals', ['state_province'], unique=False)
    op.create_table('medicines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rxnorm_cui', sa.String(length=50), nullable=True),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('form', sa.Enum('TABLET', 'CAPSULE', 'SYRUP', 'INJECTION', 'OINTMENT', 'DROPS', 'INHALER', 'PATCH', name='medicineformenum'), nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('atc_code', sa.String(length=20), nullable=True),
    sa.Column('contraindications', sa.JSON(), nullable=True),
    sa.Column('side_effects', sa.JSON(), nullable=True),
    sa.Column('is_antibiotic', sa.Boolean(), nullable=False),
    sa.Column('is_narcotic_controlled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rxnorm_cui')
    )
    op.create_index(op.f('ix_medicines_brand_name'), 'medicines', ['brand_name'], unique=False)
    op.create_index(op.f('ix_medicines_generic_name'), 'medicines', ['generic_name'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('national_health_id', sa.String(length=100), nullable=True),
    sa.Column('hospital_mrn', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='genderenum'), nullable=False),
    sa.Column('blood_group', sa.Enum('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', 'UNKNOWN', name='bloodgroupenum'), nullable=False),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_iso', sa.String(length=3), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_city'), 'patients', ['city'], unique=False)
    op.create_index(op.f('ix_patients_hospital_mrn'), 'patients', ['hospital_mrn'], unique=True)
    op.create_index(op.f('ix_patients_national_health_id'), 'patients', ['national_health_id'], unique=True)
    op.create_index(op.f('ix_patients_primary_phone'), 'patients', ['primary_phone'], unique=True)
    op.create_index(op.f('ix_patients_state_province'), 'patients', ['state_province'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=False),
    sa.Column('actor_name', sa.String(length=150), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'DOCTOR_VIEW_RECORD', 'DOCTOR_UPDATE_RECORD', 'DOCTOR_DOWNLOAD_REPORT', 'CONSENT_GIVEN', 'CONSENT_REVOKED', 'CONSENT_REJECTED', 'EMERGENCY_BYPASS', 'LOGIN', name='auditactionenum'), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=False),
    sa.Column('target_record_id', sa.String(length=36), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('previous_state_json', sa.JSON(), nullable=True),
    sa.Column('new_state_json', sa.JSON(), nullable=True),
    sa.Column('tamper_hash_chain', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_role'), 'audit_logs', ['actor_role'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_hospital_id'), 'audit_logs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_record_id'), 'audit_logs', ['target_record_id'], unique=False)
    op.create_table('central_health_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('patient_display_id', sa.String(length=50), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('last_event_type', sa.String(length=50), nullable=True),
    sa.Column('last_hospital_id', sa.String(length=36), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_central_health_records_last_synced_at'), 'central_health_records', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_central_health_records_patient_display_id'), 'central_health_records', ['patient_display_id'], unique=False)
    op.create_index(op.f('ix_central_health_records_patient_id'), 'central_health_records', ['patient_id'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('specialty_type', sa.String(length=100), nullable=False),
    sa.Column('floor_location', sa.String(length=50), nullable=True),
    sa.Column('wing_block', sa.String(length=50), nullable=True),
    sa.Column('is_emergency_dept', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'code', name='uq_hospital_dept_code')
    )
    op.create_index(op.f('ix_departments_hospital_id'), 'departments', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_departments_specialty_type'), 'departments', ['specialty_type'], unique=False)
    op.create_table('government_analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporting_date', sa.Date(), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('district_code', sa.String(length=50), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('syndromic_icd10_category', sa.String(length=50), nullable=False),
    sa.Column('patient_age_group', sa.String(length=20), nullable=False),
    sa.Column('patient_gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'UNDISCLOSED', name='genderenum'), nullable=False),
    sa.Column('total_case_count', sa.Integer(), nullable=False),
    sa.Column('emergency_escalated_count', sa.Integer(), nullable=False),
    sa.Column('avg_vitals_summary', sa.JSON(), nullable=True),
    sa.Column('geo_quadkey', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_analytics_created_at'), 'government_analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_government_analytics_district_code'), 'government_analytics', ['district_code'], unique=False)
    op.create_index(op.f('ix_government_analytics_hospital_id'), 'government_analytics', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_government_analytics_reporting_date'), 'government_analytics', ['reporting_date'], unique=False)
    op.create_index(op.f('ix_government_analytics_state_province'), 'government_analytics', ['state_province'], unique=False)
    op.create_index(op.f('ix_government_analytics_syndromic_icd10_category'), 'government_analytics', ['syndromic_icd10_category'], unique=False)
    op.create_table('medical_histories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('history_type', sa.String(length=50), nullable=False),
    sa.Column('concept_snomed_code', sa.String(length=50), nullable=True),
    sa.Column('concept_icd10_code', sa.String(length=20), nullable=True),
    sa.Column('condition_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('diagnosed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_histories_patient_id'), 'medical_histories', ['patient_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=True),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.Enum('PATIENT', 'DOCTOR', 'RECEPTIONIST', 'HOSPITAL_ADMIN', 'GOVERNMENT_ADMIN', 'KIOSK_OPERATOR', name='userroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_hospital_id'), 'users', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('license_registration_number', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('primary_specialty', sa.String(length=100), nullable=False),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('consultation_room_number', sa.String(length=50), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_doctors_license_registration_number'), 'doctors', ['license_registration_number'], unique=True)
    op.create_index(op.f('ix_doctors_primary_specialty'), 'doctors', ['primary_specialty'], unique=False)
    op.create_table('kiosk_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('device_serial_number', sa.String(length=100), nullable=False),
    sa.Column('hardware_mac_address', sa.String(length=17), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=False),
    sa.Column('kiosk_model', sa.String(length=100), nullable=False),
    sa.Column('installation_location', sa.String(length=150), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hardware_mac_address')
    )
    op.create_index(op.f('ix_kiosk_devices_device_serial_number'), 'kiosk_devices', ['device_serial_number'], unique=True)
    op.create_index(op.f('ix_kiosk_devices_hospital_id'), 'kiosk_devices', ['hospital_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', 'EMAIL', 'PUSH', 'IN_APP', 'KIOSK_AUDIO', 'CRASH_PAGER', name='notificationchannelenum'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'FAILED', 'READ', name='notificationstatusenum'), nullable=False),
    sa.Column('template_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient_destination', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_hospital_id'), 'notifications', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_notifications_patient_id'), 'notifications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_number', sa.String(length=50), nullable=False),
    sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'CHECKED_IN', 'IN_CONSULTATION', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='appointmentstatusenum'), nullable=False),
    sa.Column('chief_complaint_summary', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_number'), 'appointments', ['appointment_number'], unique=True)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_hospital_id'), 'appointments', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_scheduled_start_time'), 'appointments', ['scheduled_start_time'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('doctor_departments',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary_department', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('doctor_id', 'department_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('session_type', sa.Enum('KIOSK_HARDWARE', 'PATIENT_PORTAL', 'DOCTOR_EHR', 'ADMIN_CONSOLE', 'RECEPTION_DESK', name='sessiontypeenum'), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('kiosk_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('jwt_claims', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosk_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_kiosk_id'), 'sessions', ['kiosk_id'], unique=False)
    op.create_index(op.f('ix_sessions_patient_id'), 'sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_token_hash'), 'sessions', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_number', sa.String(length=50), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('kiosk_id', sa.String(length=36), nullable=True),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('visit_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'TRIAGE_PENDING', 'TRIAGE_COMPLETE', 'IN_QUEUE', 'DOCTOR_REVIEW', 'EMERGENCY_ESCALATED', 'DISCHARGED', 'ABANDONED', name='visitstatusenum'), nullable=False),
    sa.Column('triage_level', sa.Enum('ESI_1_RESUSCITATION', 'ESI_2_EMERGENT', 'ESI_3_URGENT', 'ESI_4_LESS_URGENT', 'ESI_5_NON_URGENT', name='triagelevelenum'), nullable=True),
    sa.Column('triage_score_reasoning', sa.Text(), nullable=True),
    sa.Column('chief_complaint_raw', sa.Text(), nullable=True),
    sa.Column('ai_soap_subjective', sa.Text(), nullable=True),
    sa.Column('ai_soap_objective', sa.Text(), nullable=True),
    sa.Column('ai_soap_assessment', sa.Text(), nullable=True),
    sa.Column('ai_soap_plan', sa.Text(), nullable=True),
    sa.Column('ai_confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fhir_encounter_payload', sa.JSON(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doctor_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosk_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_created_at'), 'visits', ['created_at'], unique=False)
    op.create_index(op.f('ix_visits_department_id'), 'visits', ['department_id'], unique=False)
    op.create_index(op.f('ix_visits_doctor_id'), 'visits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_visits_hospital_id'), 'visits', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_visits_status'), 'visits', ['status'], unique=False)
    op.create_index(op.f('ix_visits_triage_level'), 'visits', ['triage_level'], unique=False)
    op.create_index(op.f('ix_visits_visit_number'), 'visits', ['visit_number'], unique=True)
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('consent_type', sa.Enum('DATA_STORAGE', 'EHR_SYNC', 'TELECONSULT_SHARING', 'RESEARCH_ANONYMIZED', 'DOCTOR_ACCESS', 'EMERGENCY_OVERRIDE', name='consenttypeenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GRANTED', 'REJECTED', 'REVOKED', 'EXPIRED', name='consentstatusenum'), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('granted_language', sa.String(length=10), nullable=False),
    sa.Column('digital_signature_blob', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('permission_minutes', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_created_at'), 'consents', ['created_at'], unique=False)
    op.create_index(op.f('ix_consents_doctor_id'), 'consents', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_consents_expires_at'), 'consents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consents_status'), 'consents', ['status'], unique=False)
    op.create_index(op.f('ix_consents_visit_id'), 'consents', ['visit_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_type', sa.String(length=50), nullable=False),
    sa.Column('icd10_code', sa.String(length=20), nullable=False),
    sa.Column('snomed_ct_code', sa.String(length=50), nullable=True),
    sa.Column('diagnosis_name', sa.String(length=255), nullable=False),
    sa.Column('clinical_description', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('confidence_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_doctor_id'), 'diagnoses', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_icd10_code'), 'diagnoses', ['icd10_code'], unique=False)
    op.create_index(op.f('ix_diagnoses_patient_id'), 'diagnoses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_visit_id'), 'diagnoses', ['visit_id'], unique=False)
    op.create_table('medical_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('report_type', sa.Enum('LAB_BIOCHEMISTRY', 'LAB_HEMATOLOGY', 'RADIOLOGY_XRAY', 'RADIOLOGY_CT', 'RADIOLOGY_MRI', 'ECG_TRACE', 'PATHOLOGY', 'PREVIOUS_PRESCRIPTION', 'DISCHARGE_SUMMARY', 'OTHER', name='reporttypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_storage_uri', sa.Text(), nullable=False),
    sa.Column('file_mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_sha256_checksum', sa.String(length=64), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('fhir_diagnostic_report_payload', sa.JSON(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_reports_created_at'), 'medical_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_medical_reports_patient_id'), 'medical_reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medical_reports_visit_id'), 'medical_reports', ['visit_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prescription_number', sa.String(length=50), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('digital_signature_hash', sa.Text(), nullable=False),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('is_dispensed', sa.Boolean(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fhir_medication_request_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_created_at'), 'prescriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prescriptions_doctor_id'), 'prescriptions', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_patient_id'), 'prescriptions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_prescription_number'), 'prescriptions', ['prescription_number'], unique=True)
    op.create_index(op.f('ix_prescriptions_visit_id'), 'prescriptions', ['visit_id'], unique=False)
    op.create_table('queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=True),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('token_display_number', sa.String(length=20), nullable=False),
    sa.Column('priority_order_score', sa.Integer(), nullable=False),
    sa.Column('queue_status', sa.Enum('WAITING', 'CALLED', 'IN_ROOM', 'COMPLETED', 'SKIPPED', 'EMERGENCY_BYPASS', name='queuestatusenum'), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('room_entered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id')
    )
    op.create_index(op.f('ix_queue_created_at'), 'queue', ['created_at'], unique=False)
    op.create_index(op.f('ix_queue_department_id'), 'queue', ['department_id'], unique=False)
    op.create_index(op.f('ix_queue_doctor_id'), 'queue', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_queue_hospital_id'), 'queue', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_queue_patient_id'), 'queue', ['patient_id'], unique=False)
    op.create_index(op.f('ix_queue_priority_order_score'), 'queue', ['priority_order_score'], unique=False)
    op.create_index(op.f('ix_queue_queue_status'), 'queue', ['queue_status'], unique=False)
    op.create_table('vitals_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('kiosk_id', sa.String(length=36), nullable=True),
    sa.Column('systolic_bp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('diastolic_bp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mean_arterial_pressure', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heart_rate_bpm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('respiratory_rate_bpm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('oxygen_saturation_spo2', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('body_temperature_celsius', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('body_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calculated_bmi', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ecg_rhythm_summary', sa.String(length=100), nullable=True),
    sa.Column('raw_sensor_waveforms', sa.JSON(), nullable=True),
    sa.Column('is_emergency_triggered', sa.Boolean(), nullable=False),
    sa.Column('sensor_fault_flags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosk_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitals_records_created_at'), 'vitals_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_vitals_records_is_emergency_triggered'), 'vitals_records', ['is_emergency_triggered'], unique=False)
    op.create_index(op.f('ix_vitals_records_patient_id'), 'vitals_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_vitals_records_visit_id'), 'vitals_records', ['visit_id'], unique=False)
    op.create_table('ocr_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('medical_report_id', sa.String(length=36), nullable=False),
    sa.Column('ocr_engine_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'MANUALLY_CORRECTED', name='ocrstatusenum'), nullable=False),
    sa.Column('raw_extracted_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('extracted_entities_json', sa.JSON(), nullable=True),
    sa.Column('bounding_boxes_json', sa.JSON(), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('verified_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medical_report_id'], ['medical_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medical_report_id')
    )
    op.create_table('prescription_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prescription_id', sa.String(length=36), nullable=False),
    sa.Column('medicine_id', sa.String(length=36), nullable=False),
    sa.Column('dosage_instruction', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.Enum('ONCE_DAILY', 'TWICE_DAILY', 'THRICE_DAILY', 'FOUR_TIMES_DAILY', 'EVERY_4_HOURS', 'EVERY_6_HOURS', 'EVERY_8_HOURS', 'AS_NEEDED_PRN', 'STAT_IMMEDIATE', name='intakefrequencyenum'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('total_quantity_prescribed', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('special_intake_conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_medicine_id'), 'prescription_items', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    op.create_table('medicine_intake_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('prescription_item_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_intake_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dosage_amount', sa.String(length=50), nullable=False),
    sa.Column('is_taken', sa.Boolean(), nullable=False),
    sa.Column('actual_taken_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_count', sa.Integer(), nullable=False),
    sa.Column('patient_adherence_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_item_id'], ['prescription_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_intake_schedules_is_taken'), 'medicine_intake_schedules', ['is_taken'], unique=False)
    op.create_index(op.f('ix_medicine_intake_schedules_patient_id'), 'medicine_intake_schedules', ['patient_id'], unique=False)
    op.create_index(op.f('ix_medicine_intake_schedules_prescription_item_id'), 'medicine_intake_schedules', ['prescription_item_id'], unique=False)
    op.create_index(op.f('ix_medicine_intake_schedules_scheduled_intake_timestamp'), 'medicine_intake_schedules', ['scheduled_intake_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicine_intake_schedules_scheduled_intake_timestamp'), table_name='medicine_intake_schedules')
    op.drop_index(op.f('ix_medicine_intake_schedules_prescription_item_id'), table_name='medicine_intake_schedules')
    op.drop_index(op.f('ix_medicine_intake_schedules_patient_id'), table_name='medicine_intake_schedules')
    op.drop_index(op.f('ix_medicine_intake_schedules_is_taken'), table_name='medicine_intake_schedules')
    op.drop_table('medicine_intake_schedules')
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_medicine_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_table('ocr_results')
    op.drop_index(op.f('ix_vitals_records_visit_id'), table_name='vitals_records')
    op.drop_index(op.f('ix_vitals_records_patient_id'), table_name='vitals_records')
    op.drop_index(op.f('ix_vitals_records_is_emergency_triggered'), table_name='vitals_records')
    op.drop_index(op.f('ix_vitals_records_created_at'), table_name='vitals_records')
    op.drop_table('vitals_records')
    op.drop_index(op.f('ix_queue_queue_status'), table_name='queue')
    op.drop_index(op.f('ix_queue_priority_order_score'), table_name='queue')
    op.drop_index(op.f('ix_queue_patient_id'), table_name='queue')
    op.drop_index(op.f('ix_queue_hospital_id'), table_name='queue')
    op.drop_index(op.f('ix_queue_doctor_id'), table_name='queue')
    op.drop_index(op.f('ix_queue_department_id'), table_name='queue')
    op.drop_index(op.f('ix_queue_created_at'), table_name='queue')
    op.drop_table('queue')
    op.drop_index(op.f('ix_prescriptions_visit_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_prescription_number'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_patient_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_doctor_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_created_at'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_medical_reports_visit_id'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_patient_id'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_created_at'), table_name='medical_reports')
    op.drop_table('medical_reports')
    op.drop_index(op.f('ix_diagnoses_visit_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_patient_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_icd10_code'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_doctor_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_consents_visit_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_status'), table_name='consents')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_expires_at'), table_name='consents')
    op.drop_index(op.f('ix_consents_doctor_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_created_at'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_visits_visit_number'), table_name='visits')
    op.drop_index(op.f('ix_visits_triage_level'), table_name='visits')
    op.drop_index(op.f('ix_visits_status'), table_name='visits')
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_hospital_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_doctor_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_department_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_created_at'), table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_patient_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_kiosk_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('doctor_departments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_scheduled_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_hospital_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_number'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_patient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_hospital_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_kiosk_devices_hospital_id'), table_name='kiosk_devices')
    op.drop_index(op.f('ix_kiosk_devices_device_serial_number'), table_name='kiosk_devices')
    op.drop_table('kiosk_devices')
    op.drop_index(op.f('ix_doctors_primary_specialty'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_license_registration_number'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_hospital_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_hospital_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_medical_histories_patient_id'), table_name='medical_histories')
    op.drop_table('medical_histories')
    op.drop_index(op.f('ix_government_analytics_syndromic_icd10_category'), table_name='government_analytics')
    op.drop_index(op.f('ix_government_analytics_state_province'), table_name='government_analytics')
    op.drop_index(op.f('ix_government_analytics_reporting_date'), table_name='government_analytics')
    op.drop_index(op.f('ix_government_analytics_hospital_id'), table_name='government_analytics')
    op.drop_index(op.f('ix_government_analytics_district_code'), table_name='government_analytics')
    op.drop_index(op.f('ix_government_analytics_created_at'), table_name='government_analytics')
    op.drop_table('government_analytics')
    op.drop_index(op.f('ix_departments_specialty_type'), table_name='departments')
    op.drop_index(op.f('ix_departments_hospital_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_central_health_records_patient_id'), table_name='central_health_records')
    op.drop_index(op.f('ix_central_health_records_patient_display_id'), table_name='central_health_records')
    op.drop_index(op.f('ix_central_health_records_last_synced_at'), table_name='central_health_records')
    op.drop_table('central_health_records')
    op.drop_index(op.f('ix_audit_logs_target_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_hospital_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_role'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_patients_state_province'), table_name='patients')
    op.drop_index(op.f('ix_patients_primary_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_national_health_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_hospital_mrn'), table_name='patients')
    op.drop_index(op.f('ix_patients_city'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_medicines_generic_name'), table_name='medicines')
    op.drop_index(op.f('ix_medicines_brand_name'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_index(op.f('ix_hospitals_state_province'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_code'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
